Repository AY2223S1-CS2103-F09-1/tp, pull requests merged in 2022-11, with the labels that each got.

#204 Update UG V1.4 based on Dry run PE Triage
  docs/UserGuide.md
Labels: priority.Medium, documentation

#206 Yu Jie PPP V1.4
  docs/team/pokezardvgc.md
Labels: priority.Medium, documentation

#205 Minor UG fixes for FindCommand to address bug
  docs/UserGuide.md
Labels: severity.Low, documentation, ped.Tester.B

#207 Line breaks for UG for pdf conversion
  docs/UserGuide.md
Labels: severity.VeryLow, documentation

#209 Update UG to address help command issues
  docs/UserGuide.md
Labels: severity.VeryLow, documentation

#210 Update PPP (eugenelmj.md)
  docs/UserGuide.md
  docs/team/eugenelmj.md
Labels: priority.High, documentation

#211 Update PPP
  docs/UserGuide.md
  docs/team/jordanchua.md
Labels: priority.High, documentation

#213 Update Yuhao PPP
  docs/diagrams/ExitSequenceDiagram.puml
  docs/images/ExitSequenceDiagram.png
  docs/team/yh-15.md
Labels: priority.High, documentation

#214 Update PPP and project status
  docs/UserGuide.md
  docs/team/jordanchua.md
  src/main/java/jeryl/fyp/model/student/ProjectStatus.java
Labels: priority.High, documentation

#215 Minor Bug Fixes
  docs/team/jordanchua.md
  src/main/java/jeryl/fyp/model/student/ProjectStatus.java
Labels: priority.High, documentation

#216 Fix hyperlink issues
  docs/team/jordanchua.md
Labels: documentation

#217 Update common configs
  docs/SettingUp.md
  docs/Testing.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/jeryl/fyp/MainApp.java
  src/main/java/jeryl/fyp/commons/core/LogsCenter.java
Labels: documentation

#218 Update PPP + UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/LabeledUi.png
  docs/team/eugenelmj.md
  docs/team/pokezardvgc.md
  docs/team/russelldash332.md
Labels: documentation

#221 Shorten PPP to 2 pages
  docs/team/jordanchua.md
Labels: documentation

#220 Revert "List Deadline Command (V1.3)"
  src/main/java/jeryl/fyp/logic/commands/ListDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/ListDeadlineCommandParser.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
Labels: priority.High

#222 Fix typos in UG and add default command
  docs/UserGuide.md
Labels: documentation

#223 Update PPP
  docs/team/jordanchua.md
Labels: documentation

#224 Update PPP
  docs/team/sweetpotato0213.md
Labels: documentation

#219 V1.4 ped bugs
  docs/UserGuide.md
  docs/images/Priority.png
  src/main/java/jeryl/fyp/logic/commands/AddDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/commands/AddStudentCommand.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/main/java/jeryl/fyp/model/student/StudentName.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/model/student/StudentNameTest.java
Labels: type.Bug, priority.High

#225 V1.4 deadline test
  src/main/java/jeryl/fyp/commons/core/Messages.java
  src/main/java/jeryl/fyp/logic/commands/AddStudentCommand.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/logic/parser/ParserUtil.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/test/java/jeryl/fyp/logic/commands/CommandTestUtil.java
  src/test/java/jeryl/fyp/logic/commands/DeleteDeadlineCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/EditCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/AddDeadlineCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/DeleteDeadlineCommandParserTest.java
  src/test/java/jeryl/fyp/model/student/DeadlineListTest.java
  src/test/java/jeryl/fyp/model/student/DeadlineNameTest.java
  src/test/java/jeryl/fyp/model/student/DeadlineTest.java
  src/test/java/jeryl/fyp/testutil/EditStudentDescriptorBuilder.java
  src/test/java/jeryl/fyp/testutil/StudentBuilder.java
  src/test/java/jeryl/fyp/testutil/TypicalDeadlines.java
  src/test/java/jeryl/fyp/testutil/TypicalIndexes.java
  src/test/java/jeryl/fyp/testutil/TypicalStudents.java
Labels: type.Bug

#226 Update sweetpotato0213.md
  docs/team/sweetpotato0213.md
Labels: priority.Low, documentation

#229 Increase test coverage for FindCommand
  docs/UserGuide.md
  src/test/java/jeryl/fyp/logic/commands/FindProjectNameCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindStudentIdCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindStudentNameCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindTagsCommandTest.java
Labels: type.Bug

#230 Update `SortCommand` Parser Tests
  docs/team/jordanchua.md
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: priority.High

#231 Update SortCommand Test
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: documentation

#232 update PPP
  docs/team/yh-15.md
Labels: priority.Low, documentation

#233 Update FindCommand and MarkCommand diagrams for DG
  docs/DeveloperGuide.md
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/FindCommandState1.png
  docs/images/FindCommandState2.png
  docs/images/FindCommandState3.png
  docs/images/MarkCommandState1.png
  docs/images/MarkCommandState2.png
  docs/team/eugenelmj.md
Labels: documentation

#234 Update DG
  docs/DeveloperGuide.md
  docs/images/MarkCommandActivityDiagram.jpg
  docs/images/MarkCommandSequenceDiagram.jpg
  docs/images/SortCommandActivityDiagram.jpg
  docs/images/SortProjectNameCommandSequenceDiagram.jpg
  docs/images/SortProjectStatusCommandSequenceDiagram.jpg
  docs/images/SortSpecialisationCommandSequenceDiagram.jpg
Labels: priority.High, documentation

#236 V1.4_DG updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddDeadlineActivityDiagram.puml
  docs/diagrams/AddDeadlineSequenceDiagram.puml
  docs/diagrams/DeleteDeadlineActivityDiagram.puml
  docs/diagrams/DeleteDeadlineSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/EditStudentActivityDiagram.puml
  docs/diagrams/EditStudentSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/diagrams/MarkActivityDiagram.puml
  docs/images/AddDeadlineActivityDiagram.png
  docs/images/AddDeadlineSequenceDiagram.png
  docs/images/DeleteDeadlineActivityDiagram.png
  docs/images/DeleteDeadlineSequenceDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
  docs/images/EditActivityDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/HelpActivityDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/images/MarkDiagram.png
  docs/team/pokezardvgc.md
Labels: priority.High, documentation

#238 fix DG typo
  docs/DeveloperGuide.md
Labels: priority.High, documentation

#239 V1.4 UG and DG line breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low, documentation

#240 Minor updates to DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditStudentSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/team/eugenelmj.md
  docs/team/russelldash332.md
  docs/team/yh-15.md
Labels: documentation

#242 V1.4 UG and DG line breaks
  docs/DeveloperGuide.md
Labels: priority.Low, documentation

#241 Update PPP
  docs/team/jordanchua.md
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: priority.High, documentation

#243 Update stale HelpCommand DG
  docs/DeveloperGuide.md
Labels: priority.High, documentation

#244 Final DG updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: priority.High, documentation
