Repository AY2223S1-CS2103-F09-1/tp, pull requests merged in 2022-10, with the labels that each got.

#68 Update DG for v1.1
  docs/DeveloperGuide.md
Labels: documentation

#76 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#83 Fix trailing whitespaces in DG
  docs/DeveloperGuide.md
Labels: documentation

#84 V1.2 mark command
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/StudentID.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#94 Show missing StudentCard and WelcomeBox
  src/main/java/jeryl/fyp/ui/HelpWindow.java
  src/main/java/jeryl/fyp/ui/MainWindow.java
  src/main/java/jeryl/fyp/ui/StatusBarFooter.java
  src/main/java/jeryl/fyp/ui/StudentCard.java
  src/main/java/jeryl/fyp/ui/WelcomeBox.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/WelcomeBox.fxml
Labels: priority.High, severity.High

#95 Add JUnit tests and remove `Phone`
  src/main/java/jeryl/fyp/logic/parser/CliSyntax.java
  src/main/java/jeryl/fyp/logic/parser/ParserUtil.java
  src/main/java/jeryl/fyp/model/student/Phone.java
  src/test/java/jeryl/fyp/logic/commands/CommandTestUtil.java
  src/test/java/jeryl/fyp/logic/commands/EditStudentDescriptorTest.java
  src/test/java/jeryl/fyp/logic/parser/ParserUtilTest.java
  src/test/java/jeryl/fyp/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/jeryl/fyp/model/student/PhoneTest.java
  src/test/java/jeryl/fyp/model/student/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/jeryl/fyp/model/student/StudentIdTest.java
  src/test/java/jeryl/fyp/model/student/StudentTest.java
  src/test/java/jeryl/fyp/storage/JsonAdaptedStudentTest.java
Labels: priority.High, severity.Low

#97 Update Mark Command
  src/main/java/jeryl/fyp/commons/core/Messages.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/logic/commands/MarkCommand.java
  src/main/java/jeryl/fyp/logic/parser/AddCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/ArgumentMultimap.java
  src/main/java/jeryl/fyp/logic/parser/MarkCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/ParserUtil.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/main/java/jeryl/fyp/model/student/ProjectName.java
  src/main/java/jeryl/fyp/model/student/ProjectStatus.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/main/java/jeryl/fyp/model/util/SampleDataUtil.java
  src/main/java/jeryl/fyp/storage/JsonAdaptedStudent.java
  src/main/java/jeryl/fyp/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableFypManagerTest/duplicateStudentFypManager.json
  src/test/data/JsonSerializableFypManagerTest/typicalStudentsFypManager.json
  src/test/java/jeryl/fyp/logic/commands/AddCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/CommandTestUtil.java
  src/test/java/jeryl/fyp/logic/commands/MarkCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
  src/test/java/jeryl/fyp/model/student/ProjectStatusTest.java
  src/test/java/jeryl/fyp/storage/JsonAdaptedStudentTest.java
  src/test/java/jeryl/fyp/testutil/StudentBuilder.java
  src/test/java/jeryl/fyp/testutil/TypicalStudents.java
Labels: priority.High

#99 Update User Guide for Mark Command
  docs/UserGuide.md
Labels: priority.High, documentation

#102 Enhance HelpCommand
  src/main/java/jeryl/fyp/logic/commands/HelpAddCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpDeleteCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpFindCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpListCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpMarkCommand.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/HelpCommandParser.java
Labels: type.Enhancement, priority.High, severity.High

#104 Resolve various issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/jeryl/fyp/logic/commands/AddCommand.java
  src/main/java/jeryl/fyp/logic/commands/DeleteCommand.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpCommand.java
  src/main/java/jeryl/fyp/logic/commands/MarkCommand.java
  src/main/java/jeryl/fyp/logic/parser/AddCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/CliSyntax.java
  src/main/java/jeryl/fyp/logic/parser/EditCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/MarkCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/ParserUtil.java
  src/main/java/jeryl/fyp/model/student/NameContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/ProjectStatus.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/main/java/jeryl/fyp/model/student/StudentName.java
  src/main/java/jeryl/fyp/model/student/StudentNameContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/main/java/jeryl/fyp/model/util/SampleDataUtil.java
  src/main/java/jeryl/fyp/storage/JsonAdaptedStudent.java
  src/main/java/jeryl/fyp/ui/StudentCard.java
  src/test/java/jeryl/fyp/logic/LogicManagerTest.java
  src/test/java/jeryl/fyp/logic/commands/AddCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/CommandTestUtil.java
  src/test/java/jeryl/fyp/logic/commands/DeleteCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/EditCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/EditStudentDescriptorTest.java
  src/test/java/jeryl/fyp/logic/commands/FindCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/MarkCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/AddCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/DeleteCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/EditCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
  src/test/java/jeryl/fyp/logic/parser/MarkCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/ParserUtilTest.java
  src/test/java/jeryl/fyp/model/ModelManagerTest.java
  src/test/java/jeryl/fyp/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/jeryl/fyp/model/student/NameTest.java
  src/test/java/jeryl/fyp/model/student/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/jeryl/fyp/model/student/StudentNameContainsKeywordsPredicateTest.java
  src/test/java/jeryl/fyp/model/student/StudentNameTest.java
  src/test/java/jeryl/fyp/model/student/StudentTest.java
  src/test/java/jeryl/fyp/storage/JsonAdaptedStudentTest.java
  src/test/java/jeryl/fyp/testutil/EditStudentDescriptorBuilder.java
  src/test/java/jeryl/fyp/testutil/StudentBuilder.java
  src/test/java/jeryl/fyp/testutil/StudentUtil.java
  src/test/java/jeryl/fyp/testutil/TypicalStudents.java
Labels: type.Enhancement, priority.High, severity.Medium, documentation

#113 Update Sequence Diagram
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/index.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/test/data/JsonSerializableFypManagerTest/typicalStudentsFypManager.json
Labels: priority.High, documentation

#112 Add MarkCommand in DeveloperGuide
  docs/DeveloperGuide.md
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/MarkCommandState1.png
  docs/images/MarkCommandState2.png
Labels: priority.High, documentation

#116 Update DeveloperGuide and UML diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentActivityDiagram.puml
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/images/AddStudentActivityDiagram.png
  docs/images/AddStudentSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/tracing/LogicSequenceDiagram.png
Labels: priority.High, documentation

#117 Update MarkCommand Sequence Diagram
  docs/DeveloperGuide.md
  docs/images/MarkCommandSequenceDiagram.png
Labels: documentation

#119 Update delete command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteStudentActivityDiagram.puml
  docs/images/DeleteStudentActivityDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
Labels: priority.High, documentation

#118 Update FindCommand for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FindCommandSequenceDiagram.png
  docs/images/FindCommandState1.png
  docs/images/FindCommandState2.png
Labels: priority.High, severity.High, documentation

#121 UI changes to match mockup
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/jeryl/fyp/ui/MainWindow.java
  src/main/java/jeryl/fyp/ui/StudentCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StudentCard.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListPanel.fxml
  src/main/resources/view/WelcomeBox.fxml
Labels: priority.High, documentation

#123 Enable assertions on Gradle
  build.gradle
Labels: priority.High

#125 Enhance FindCommand for v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/jeryl/fyp/logic/commands/FindCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindProjectNameCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindStudentIdCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindStudentNameCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindTagsCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpFindCommand.java
  src/main/java/jeryl/fyp/logic/parser/FindProjectNameCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/FindStudentIdCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/FindStudentNameCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/FindTagsCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/HelpCommandParser.java
  src/main/java/jeryl/fyp/model/student/FieldContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/ProjectNameContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/StudentIdContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/StudentNameContainsKeywordsPredicate.java
  src/main/java/jeryl/fyp/model/student/TagsContainKeywordsPredicate.java
  src/test/java/jeryl/fyp/logic/commands/FindProjectNameCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindStudentIdCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindStudentNameCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/FindTagsCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/FindProjectNameCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FindStudentIdCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FindStudentNameCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FindTagsCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: type.Enhancement, type.Task, priority.High, severity.Medium, documentation

#130 feat: Split uncompleted and completed student list
  src/main/java/jeryl/fyp/commons/core/Messages.java
  src/main/java/jeryl/fyp/logic/Logic.java
  src/main/java/jeryl/fyp/logic/LogicManager.java
  src/main/java/jeryl/fyp/logic/commands/DeleteDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/commands/MarkCommand.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/main/java/jeryl/fyp/model/ReadOnlyFypManager.java
  src/main/java/jeryl/fyp/model/student/Deadline.java
  src/main/java/jeryl/fyp/model/student/DeadlineList.java
  src/main/java/jeryl/fyp/model/student/DeadlineListTemplate.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/main/java/jeryl/fyp/model/student/exceptions/StudentNotFoundException.java
  src/main/java/jeryl/fyp/ui/CommandBox.java
  src/main/java/jeryl/fyp/ui/CompletedStudentListPanel.java
  src/main/java/jeryl/fyp/ui/CompletedStudentListTitle.java
  src/main/java/jeryl/fyp/ui/MainWindow.java
  src/main/java/jeryl/fyp/ui/StudentCard.java
  src/main/java/jeryl/fyp/ui/UncompletedStudentListPanel.java
  src/main/java/jeryl/fyp/ui/UncompletedStudentListTitle.java
  src/main/resources/images/mail.png
  src/main/resources/view/CompletedStudentListPanel.fxml
  src/main/resources/view/CompletedStudentListTitle.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentCard.fxml
  src/main/resources/view/UncompletedStudentListPanel.fxml
  src/main/resources/view/UncompletedStudentListTitle.fxml
  src/test/java/jeryl/fyp/logic/commands/AddDeadlineCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/model/FypManagerTest.java
Labels: type.Enhancement, type.Task, priority.High

#134 Change student uniqueness check to `StudentId`
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/model/student/Student.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/model/student/StudentTest.java
Labels: priority.Medium

#126 Update SortCommand for v1.3
  docs/DeveloperGuide.md
  docs/images/MarkCommandSequenceDiagram.jpg
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/SortProjectStatusCommandSequenceDiagram.jpg
  docs/images/SortSpecialisationCommandSequenceDiagram.jpg
  src/main/java/jeryl/fyp/logic/Logic.java
  src/main/java/jeryl/fyp/logic/LogicManager.java
  src/main/java/jeryl/fyp/logic/commands/ClearCommand.java
  src/main/java/jeryl/fyp/logic/commands/CommandResult.java
  src/main/java/jeryl/fyp/logic/commands/ExitCommand.java
  src/main/java/jeryl/fyp/logic/commands/HelpCommand.java
  src/main/java/jeryl/fyp/logic/commands/SortProjectStatusCommand.java
  src/main/java/jeryl/fyp/logic/commands/SortSpecialisationCommand.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/HelpCommandParser.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/main/java/jeryl/fyp/ui/MainWindow.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/CommandResultTest.java
  src/test/java/jeryl/fyp/logic/commands/ExitCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/HelpCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/SortProjectStatusCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/SortSpecialisationCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: type.Enhancement, priority.High, severity.High

#136 User Guide minor changes
  docs/UserGuide.md
  src/main/java/jeryl/fyp/logic/Logic.java
Labels: priority.High, severity.Low, documentation

#137 Update Edit command
  src/main/java/jeryl/fyp/commons/core/Messages.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/logic/parser/EditCommandParser.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/EditCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/EditCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
Labels: type.Enhancement, priority.High

#140 Update UG
  docs/UserGuide.md
Labels: priority.Medium, documentation

#141 feat: Consolidate v1.3b
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/images/Ui.png
  src/main/java/jeryl/fyp/MainApp.java
  src/main/java/jeryl/fyp/logic/Logic.java
  src/main/java/jeryl/fyp/logic/LogicManager.java
  src/main/java/jeryl/fyp/logic/commands/AddDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/commands/AddStudentCommand.java
  src/main/java/jeryl/fyp/logic/commands/CommandResult.java
  src/main/java/jeryl/fyp/logic/commands/DeleteDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/commands/DeleteStudentCommand.java
  src/main/java/jeryl/fyp/logic/commands/EditCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindCommand.java
  src/main/java/jeryl/fyp/logic/commands/FindStudentIdCommand.java
  src/main/java/jeryl/fyp/logic/commands/ListCommand.java
  src/main/java/jeryl/fyp/logic/commands/MarkCommand.java
  src/main/java/jeryl/fyp/logic/commands/SortProjectNameCommand.java
  src/main/java/jeryl/fyp/logic/commands/SortProjectStatusCommand.java
  src/main/java/jeryl/fyp/logic/parser/ArgumentTokenizer.java
  src/main/java/jeryl/fyp/logic/parser/CliSyntax.java
  src/main/java/jeryl/fyp/logic/parser/EditCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/HelpCommandParser.java
  src/main/java/jeryl/fyp/logic/parser/ParserUtil.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/main/java/jeryl/fyp/model/ReadOnlyFypManager.java
  src/main/java/jeryl/fyp/model/student/Deadline.java
  src/main/java/jeryl/fyp/model/student/DeadlineList.java
  src/main/java/jeryl/fyp/model/student/StudentId.java
  src/main/java/jeryl/fyp/model/student/UniqueStudentList.java
  src/main/java/jeryl/fyp/storage/JsonAdaptedDeadline.java
  src/main/java/jeryl/fyp/ui/MainWindow.java
  src/test/java/jeryl/fyp/logic/LogicManagerTest.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/CommandTestUtil.java
  src/test/java/jeryl/fyp/logic/commands/EditCommandTest.java
  src/test/java/jeryl/fyp/logic/commands/EditStudentDescriptorTest.java
  src/test/java/jeryl/fyp/logic/commands/SortProjectNameCommandTest.java
  src/test/java/jeryl/fyp/logic/parser/AddStudentCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/EditCommandParserTest.java
  src/test/java/jeryl/fyp/logic/parser/FypManagerParserTest.java
  src/test/java/jeryl/fyp/model/FypManagerTest.java
  src/test/java/jeryl/fyp/testutil/EditStudentDescriptorBuilder.java
  src/test/java/jeryl/fyp/testutil/StudentUtil.java
  src/test/java/jeryl/fyp/testutil/TypicalStudents.java
Labels: priority.High, severity.High, documentation

#142 Fix typo on index.md
  docs/index.md
Labels: documentation

#143 Refine UG numberings
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, documentation

#155 List Deadline Command (V1.3)
  src/main/java/jeryl/fyp/logic/commands/ListDeadlineCommand.java
  src/main/java/jeryl/fyp/logic/parser/FypManagerParser.java
  src/main/java/jeryl/fyp/logic/parser/ListDeadlineCommandParser.java
  src/main/java/jeryl/fyp/model/FypManager.java
  src/main/java/jeryl/fyp/model/Model.java
  src/main/java/jeryl/fyp/model/ModelManager.java
  src/test/java/jeryl/fyp/logic/commands/AddStudentCommandTest.java
Labels: type.Enhancement, priority.High
